apiVersion: v1
kind: Service
metadata:
  name: __CUSTOMERWEB__
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.webinternalip }}  
  ports:
  - port: 3000
  selector:
    app: __CUSTOMERWEB__