export const CLAIMS_AND_CLINICAL_RESOURCE = {
	claims: 'ExplanationOfBenefit',
	allergy: 'AllergyIntolerance',
	condition: 'Condition',
	medication: 'MedicationRequest',
	prescription: 'MedicationStatement',
	immunization: 'Immunization',
	procedure: 'Procedures',
	carePlan: 'CarePlan',
	diagnosticReport: 'DiagnosticReport',
	documentReference: 'DocumentReference',
	observation: 'Observation',
	encounter: 'Encounter',
	insurance: 'Insurance',
	healthcare: 'HealthcareService',
	organization: 'Organization',
	practitioner: 'Practitioner',
	location: 'Location',
	role: 'PractitionerRole',
	affiliation: 'Affiliation',
	list: 'List',
	knowledge: 'MedicationKnowledge',
};

export const AUTH_GRANT_TYPES = {
	password: 'password',
	authorizationCode: 'authorization_code',
	clientCredentials: 'client_credentials',
	implicit: 'implicit',
};
export const CLINICAL_CATEGORY = ['AllergyIntolerance','Procedures', 'Immunization', 'Condition', 'Medication', 'Practitioner','MedicationStatement','MedicationRequest', 'DocumentReference', 'Observation', 'CarePlan', 'CareTeam','Coverage', 'Device', 'DiagnosticReport'];
export const CLAIMS_CATEGORY = ['ExplanationOfBenefit', 'Organization', 'Practitioner'];
export const SECURE_US_DRUG = ['List', 'MedicationKnowledge'];
export const FORMULARY_NET = ['Practitioner', 'HealthcareService', 'Organization','Location','OrganizationAffiliation', 'Insurance'];

export const TimelineResources = [
	{
		name: 'Claims',
		color: '#6BE38D',
		resource: 'ExplanationOfBenefit',
		displayKeys: ['Substance', 'Date'],
		screen: 'ClaimsScreen',
		category: CLAIMS_CATEGORY,
	},
	{
		name: 'Allergy',
		color: '#FFC657',
		resource: 'AllergyIntolerance',
		displayKeys: ['Substance', 'Date'],
		screen: 'AllergyScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Procedures',
		color: '#FF7C53',
		resource: 'Procedures',
		displayKeys: ['Name', 'Date Performed'],
		screen: 'ProcedureScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Immunizations',
		color: '#FFC657',
		resource: 'Immunization',
		displayKeys: ['Vaccine Code', 'Date Administered'],
		screen: 'ImmunizationScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Conditions',
		color: '#A56BD2',
		resource: 'Condition',
		displayKeys: ['Condition', 'Date'],
		screen: 'ConditionScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Medication',
		color: '#6BE38D',
		resource: 'MedicationStatement',
		displayKeys: ['Medication', 'Date Prescribed'],
		screen: 'MedicationScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Prescription',
		color: '#FF7C53',
		resource: 'MedicationRequest',
		displayKeys: ['Medication', 'Date Prescribed'],
		screen: 'PrescriptionScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Observation',
		color: '#FFC657',
		resource: 'Observation',
		displayKeys: ['Date observed', ''],
		screen: 'ObservationScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'CarePlan',
		color: '#A56BD2',
		resource: 'CarePlan',
		displayKeys: ['Activities', 'Timing'],
		screen: 'CareplanScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'DiagnosticReport',
		color: '#6BE38D',
		resource: 'DiagnosticReport',
		displayKeys: ['Category', 'Date'],
		screen: 'DiagnosticReportScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'DocumentReference',
		color: '#FF7C53',
		resource: 'DocumentReference',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Encounter',
		color: '#A56BD2',
		resource: 'Encounter',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: CLINICAL_CATEGORY,
	},
	{
		name: 'Insurance',
		color: '#6BE38D',
		resource: 'Insurance',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Healthcare',
		color: '#FF7C53',
		resource: 'HealthcareService',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Organization',
		color: '#FFC657',
		resource: 'Organization',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Practitioner',
		color: '#A56BD2',
		resource: 'Practitioner',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Location',
		color: '#6BE38D',
		resource: 'Location',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'PractitionerRole',
		color: '#A56BD2',
		resource: 'PractitionerRole',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Organization Affiliation',
		color: '#FFC657',
		resource: 'Affiliation',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'Knowledge',
		color: '#F07A51',
		resource: 'MedicationKnowledge',
		displayKeys: ['Category', 'Date Created'],
		screen: 'KnowledgeScreen',
		category: FORMULARY_NET,
	},
	{
		name: 'List',
		color: '#6BE38D',
		resource: 'List',
		displayKeys: ['Category', 'Date Created'],
		screen: 'ListScreen',
		category: FORMULARY_NET,
	},
];

export const TimelineDateFormat = 'D MMM, YYYY';
