export const CLAIMS_AND_CLINICAL_RESOURCE = {
	claims: 'ExplanationOfBenefit',
	allergy: 'AllergyIntolerance',
	condition: 'Condition',
	medication: 'MedicationRequest',
	prescription: 'MedicationStatement',
	immunization: 'Immunization',
	procedure: 'Procedures',
	carePlan: 'CarePlan',
	diagnosticReport: 'DiagnosticReport',
	documentReference: 'DocumentReference',
	observation: 'Observation',
	encounter: 'Encounter',
	insurance: 'Insurance',
	healthcare: 'Healthcare',
	organization: 'Organization',
	practicioner: 'Practicioner',
	location: 'Location',
	role: 'Role',
	affiliation: 'Affiliation',
};

export const AUTH_GRANT_TYPES = {
	password: 'password',
	authorizationCode: 'authorization_code',
	clientCredentials: 'client_credentials',
	implicit: 'implicit',
};

export const TimelineResources = [
	{
		name: 'Claims',
		color: '#6BE38D',
		resource: 'ExplanationOfBenefit',
		displayKeys: ['Substance', 'Date'],
		screen: 'ClaimsScreen',
		category: 'a',
	},
	{
		name: 'Allergy',
		color: '#FFC657',
		resource: 'AllergyIntolerance',
		displayKeys: ['Substance', 'Date'],
		screen: 'AllergyScreen',
		category: 'a',
	},
	{
		name: 'Procedures',
		color: '#FF7C53',
		resource: 'Procedures',
		displayKeys: ['Name', 'Date Performed'],
		screen: 'ProcedureScreen',
		category: 'a',
	},
	{
		name: 'Immunizations',
		color: '#FFC657',
		resource: 'Immunization',
		displayKeys: ['Vaccine Code', 'Date Administered'],
		screen: 'ImmunizationScreen',
		category: 'a',
	},
	{
		name: 'Conditions',
		color: '#A56BD2',
		resource: 'Condition',
		displayKeys: ['Condition', 'Date'],
		screen: 'ConditionScreen',
		category: 'a',
	},
	{
		name: 'Medication',
		color: '#6BE38D',
		resource: 'MedicationStatement',
		displayKeys: ['Medication', 'Date Prescribed'],
		screen: 'MedicationScreen',
		category: 'a',
	},
	{
		name: 'Prescription',
		color: '#FF7C53',
		resource: 'MedicationRequest',
		displayKeys: ['Medication', 'Date Prescribed'],
		screen: 'PrescriptionScreen',
		category: 'a',
	},
	{
		name: 'Observation',
		color: '#FFC657',
		resource: 'Observation',
		displayKeys: ['Date observed', ''],
		screen: 'ObservationScreen',
		category: 'b',
	},
	{
		name: 'CarePlan',
		color: '#A56BD2',
		resource: 'CarePlan',
		displayKeys: ['Activities', 'Timing'],
		screen: 'CareplanScreen',
		category: 'b',
	},
	{
		name: 'DiagnosticReport',
		color: '#6BE38D',
		resource: 'DiagnosticReport',
		displayKeys: ['Category', 'Date'],
		screen: 'DiagnosticReportScreen',
		category: 'b',
	},
	{
		name: 'DocumentReference',
		color: '#FF7C53',
		resource: 'DocumentReference',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'b',
	},
	{
		name: 'Encounter',
		color: '#A56BD2',
		resource: 'Encounter',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'b',
	},
	{
		name: 'Insurance',
		color: '#6BE38D',
		resource: 'Insurance',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'b',
	},
	{
		name: 'Healthcare',
		color: '#FF7C53',
		resource: 'Healthcare',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'b',
	},
	{
		name: 'Organization',
		color: '#FFC657',
		resource: 'Organization',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'b',
	},
	{
		name: 'Practicioner',
		color: '#A56BD2',
		resource: 'Practicioner',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'c',
	},
	{
		name: 'Location',
		color: '#6BE38D',
		resource: 'Location',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'c',
	},
	{
		name: 'Role',
		color: '#A56BD2',
		resource: 'Role',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'c',
	},
	{
		name: 'Affiliation',
		color: '#FFC657',
		resource: 'Affiliation',
		displayKeys: ['Category', 'Date Created'],
		screen: 'DocumentReferenceScreen',
		category: 'c',
	},
];

export const TimelineDateFormat = 'D MMM, YYYY';
